name: ticket-booking

services:
  gateway:
    build: ../backend/gateway/
    ports:
      - "8080:8080"

  user-service:
    build: ../backend/user-service/
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/users_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver

  event-service:
    build: ../backend/event-service/
    ports:
      - "8082:8080"

  booking-service:
    build: ../backend/booking-service/
    ports:
      - "8083:8080"

  payment-service:
    build: ../backend/payment-service/
    ports:
      - "8084:8080"

  notification-service:
    build: ../backend/notification-service/
    ports:
      - "8085:8080"

  postgres:
    image: postgres:18.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
          - pgdata:/var/lib/postgresql
          - ./db/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"    # AMQP port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata: